name: Create or Update Release and Upload Assets

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (tag) for the release"
        required: false

      is_patch:
        description: "It is a patch release"
        required: false
        default: false
        type: boolean

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Version
        id: determine_version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "NEXT_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            git fetch --tags

            chmod +x ./scripts/bump-version.sh
            
            if [ "${{ github.event.inputs.is_patch }}" == true ]; then
              current_version=$(git describe --abbrev=0 --tags)
              next_version=$(./scripts/bump-version.sh --patch "$current_version")
            else
              current_version=$(git describe --abbrev=0 --tags)
              next_version=$(./scripts/bump-version.sh "$current_version")
            fi
            
            echo "NEXT_VERSION=$next_version" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        id: create_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.NEXT_VERSION }} --title "Release ${{ env.NEXT_VERSION }}" --generate-notes

      - name: Find and Upload Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in ./release/*; do
            gh release upload ${{ env.NEXT_VERSION }} "$file"  --clobber
          done
