name: Create Release and Upload Assets

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: List contents of '/release' directory
        run: ls -l release

      - name: Navigate to './release'
        run: cd ./release || { echo "Directory not found"; exit 1; }

      - name: Check current directory after cd
        run: |
          pwd
          ls -l

      - name: Tree Directory
        run: |
          tree -a . -I ".git|res/*"

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in *; do
            gh release upload ${{ github.ref }} "$file" --clobber
          done
